### ISSUE TITLE
Redundant errors shown in the console also in the simple use case

### ISSUE THREAD

**Issue by bogeeee** [bvaughn/react-error-boundary#209]
Hope it's not a duplicate of [this](https://github.com/bvaughn/react-error-boundary/issues/189) but it's a different usage here.

- `react-error-boundary` version: 4.1.2
- `react` version: 18.3.1

Relevant code or config

```js
import React from "react";
import {createRoot} from "react-dom/client";
import {ErrorBoundary} from "react-error-boundary";


const MyComponent = (props) => {
    throw new Error("Some error");
}

function App(props) {
    return <div>
        <ErrorBoundary fallback="uuups" onError={ (error, info) => console.log("Error: " + error.message)}>
            <MyComponent/>
        </ErrorBoundary>
    </div>
}

createRoot(document.getElementById("root")).render(<App/>);
```

Expected:
It should only log "Error: Some error" by my own handler once. (i wrap it. I supply a logger -> i really consider this "caught")

Actual:
It additionally spams the console with 3 Errors:

```
index.tsx:7 Uncaught Error: Some error
    at MyComponent (index.tsx:7:11)
    at renderWithHooks (react-dom_client.js?v=f8c15ab1:11546:26)
    at mountIndeterminateComponent (react-dom_client.js?v=f8c15ab1:14924:21)
    at beginWork (react-dom_client.js?v=f8c15ab1:15912:22)
    at HTMLUnknownElement.callCallback2 (react-dom_client.js?v=f8c15ab1:3672:22)
    at Object.invokeGuardedCallbackDev (react-dom_client.js?v=f8c15ab1:3697:24)
    at invokeGuardedCallback (react-dom_client.js?v=f8c15ab1:3731:39)
    at beginWork$1 (react-dom_client.js?v=f8c15ab1:19763:15)
    at performUnitOfWork (react-dom_client.js?v=f8c15ab1:19199:20)
    at workLoopSync (react-dom_client.js?v=f8c15ab1:19135:13)
MyComponent @ index.tsx:7
renderWithHooks @ react-dom_client.js?v=f8c15ab1:11546
mountIndeterminateComponent @ react-dom_client.js?v=f8c15ab1:14924
beginWork @ react-dom_client.js?v=f8c15ab1:15912
callCallback2 @ react-dom_client.js?v=f8c15ab1:3672
invokeGuardedCallbackDev @ react-dom_client.js?v=f8c15ab1:3697
invokeGuardedCallback @ react-dom_client.js?v=f8c15ab1:3731
beginWork$1 @ react-dom_client.js?v=f8c15ab1:19763
performUnitOfWork @ react-dom_client.js?v=f8c15ab1:19199
workLoopSync @ react-dom_client.js?v=f8c15ab1:19135
renderRootSync @ react-dom_client.js?v=f8c15ab1:19114
performConcurrentWorkOnRoot @ react-dom_client.js?v=f8c15ab1:18676
workLoop @ react-dom_client.js?v=f8c15ab1:195
flushWork @ react-dom_client.js?v=f8c15ab1:174
performWorkUntilDeadline @ react-dom_client.js?v=f8c15ab1:382
index.tsx:7 Uncaught Error: Some error
    at MyComponent (index.tsx:7:11)
    at renderWithHooks (react-dom_client.js?v=f8c15ab1:11546:26)
    at mountIndeterminateComponent (react-dom_client.js?v=f8c15ab1:14924:21)
    at beginWork (react-dom_client.js?v=f8c15ab1:15912:22)
    at HTMLUnknownElement.callCallback2 (react-dom_client.js?v=f8c15ab1:3672:22)
    at Object.invokeGuardedCallbackDev (react-dom_client.js?v=f8c15ab1:3697:24)
    at invokeGuardedCallback (react-dom_client.js?v=f8c15ab1:3731:39)
    at beginWork$1 (react-dom_client.js?v=f8c15ab1:19763:15)
    at performUnitOfWork (react-dom_client.js?v=f8c15ab1:19199:20)
    at workLoopSync (react-dom_client.js?v=f8c15ab1:19135:13)
MyComponent @ index.tsx:7
renderWithHooks @ react-dom_client.js?v=f8c15ab1:11546
mountIndeterminateComponent @ react-dom_client.js?v=f8c15ab1:14924
beginWork @ react-dom_client.js?v=f8c15ab1:15912
callCallback2 @ react-dom_client.js?v=f8c15ab1:3672
invokeGuardedCallbackDev @ react-dom_client.js?v=f8c15ab1:3697
invokeGuardedCallback @ react-dom_client.js?v=f8c15ab1:3731
beginWork$1 @ react-dom_client.js?v=f8c15ab1:19763
performUnitOfWork @ react-dom_client.js?v=f8c15ab1:19199
workLoopSync @ react-dom_client.js?v=f8c15ab1:19135
renderRootSync @ react-dom_client.js?v=f8c15ab1:19114
recoverFromConcurrentError @ react-dom_client.js?v=f8c15ab1:18734
performConcurrentWorkOnRoot @ react-dom_client.js?v=f8c15ab1:18682
workLoop @ react-dom_client.js?v=f8c15ab1:195
flushWork @ react-dom_client.js?v=f8c15ab1:174
performWorkUntilDeadline @ react-dom_client.js?v=f8c15ab1:382
react-dom_client.js?v=f8c15ab1:14030 The above error occurred in the <MyComponent> component:

    at MyComponent (http://localhost:5173/index.tsx?t=1732566624516:5:9)
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=70e49b11:16:5)
    at div
    at App

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom_client.js?v=f8c15ab1:14030
callback @ react-dom_client.js?v=f8c15ab1:14076
callCallback @ react-dom_client.js?v=f8c15ab1:11246
commitUpdateQueue @ react-dom_client.js?v=f8c15ab1:11263
commitLayoutEffectOnFiber @ react-dom_client.js?v=f8c15ab1:17073
commitLayoutMountEffects_complete @ react-dom_client.js?v=f8c15ab1:17978
commitLayoutEffects_begin @ react-dom_client.js?v=f8c15ab1:17967
commitLayoutEffects @ react-dom_client.js?v=f8c15ab1:17918
commitRootImpl @ react-dom_client.js?v=f8c15ab1:19351
commitRoot @ react-dom_client.js?v=f8c15ab1:19275
finishConcurrentRender @ react-dom_client.js?v=f8c15ab1:18758
performConcurrentWorkOnRoot @ react-dom_client.js?v=f8c15ab1:18716
workLoop @ react-dom_client.js?v=f8c15ab1:195
flushWork @ react-dom_client.js?v=f8c15ab1:174
performWorkUntilDeadline @ react-dom_client.js?v=f8c15ab1:382
index.tsx:12 Error: Some error
```

Suggested solution:
Somebody fix it, please xD xD xD cause i'm currently busy, fixing bugs for my own open source libs...

**Comment by bvaughn** [comment]
> Expected:
It should only log "Error: Some error" by my own handler once. (i wrap it. I supply a logger -> i really consider this "caught")

This is not how React error boundaries work. React itself is logging your component errors, not this library.

**Comment by bogeeee** [comment]
Thx for the clarification!
